"""add notifications

Revision ID: 642684ee5d2e
Revises: fe873d9c48c0
Create Date: 2026-01-01 19:47:47.848637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642684ee5d2e'
down_revision = 'fe873d9c48c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'assignments', ['assignment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['actor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_read')
        batch_op.drop_column('message')
        batch_op.drop_column('assignment_id')
        batch_op.drop_column('actor_id')

    # ### end Alembic commands ###
